"""Initial migration: create tables and add link column to jobs

Revision ID: 0eebd141ea35
Revises: 
Create Date: 2025-09-07 04:09:14.426610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eebd141ea35'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('site', sa.String(), nullable=False))
    op.add_column('jobs', sa.Column('job_url', sa.Text(), nullable=False))
    op.add_column('jobs', sa.Column('job_url_direct', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('date_posted', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('job_level', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('company_industry', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('company_url', sa.Text(), nullable=True))
    op.drop_column('jobs', 'source')
    op.drop_column('jobs', 'link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('link', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('jobs', 'company_url')
    op.drop_column('jobs', 'company_industry')
    op.drop_column('jobs', 'job_level')
    op.drop_column('jobs', 'date_posted')
    op.drop_column('jobs', 'job_url_direct')
    op.drop_column('jobs', 'job_url')
    op.drop_column('jobs', 'site')
    # ### end Alembic commands ###
