SITE_NAME = "linkedin"

# Job Posting Keys
ID = "id"
SITE = "site"
JOB_URL = "job_url"
JOB_URL_DIRECT = "job_url_direct"
TITLE = "title"
COMPANY = "company"
LOCATION = "location"
DATE_POSTED = "date_posted"
JOB_LEVEL = "job_level"
DESCRIPTION = "description"
COMPANY_INDUSTRY = "company_industry"
COMPANY_URL = "company_url"
